# Generated by Django 6.0.3 on 2026-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('rate_type', models.CharField(max_length=100)),
                ('rate_value', models.FloatField()),
                ('effective_date', models.DateField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'rate_type'], name='rates_rate_provide_b69d88_idx'), models.Index(fields=['effective_date'], name='rates_rate_effecti_1bb52c_idx'), models.Index(fields=['ingested_at'], name='rates_rate_ingeste_582518_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'rate_type', 'effective_date'), name='unique_rate_record')],
            },
        ),
    ]
