# Generated by Django 6.0.3 on 2026-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rate',
            name='rates_rate_provide_b69d88_idx',
        ),
        migrations.RemoveIndex(
            model_name='rate',
            name='rates_rate_effecti_1bb52c_idx',
        ),
        migrations.RemoveIndex(
            model_name='rate',
            name='rates_rate_ingeste_582518_idx',
        ),
        migrations.AddField(
            model_name='rate',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='raw_response_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
