# Generated by Django 6.0.3 on 2026-04-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_remove_rate_rates_rate_provide_b69d88_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
